# ------------------------------------------------------------
# USB Gadget configuration
# ------------------------------------------------------------

# ecm   = macOS / Linux
# rndis = Windows
PROFILE=ecm

# Aggiunge una seriale USB CDC ACM
ENABLE_ACM=yes

# IP statico lato Raspberry
USB_ADDRESS=192.168.2.3/24

# Non impostiamo deliberatamente un gateway.
# wlan0 può quindi continuare a essere la default route.

# USB descriptors
MANUFACTURER="Kali Linux"
PRODUCT="Raspberry Pi Zero 2 W USB Gadget"

# Solo per laboratorio/personale.
ID_VENDOR=0x1d6b
ID_PRODUCT=0x0104

BCD_DEVICE=0x0100
BCD_USB=0x0200

# Assorbimento dichiarato in mA
MAX_POWER_MA=250